### ISSUE TITLE
Lean 3.5.0c Milestone

### ISSUE THREAD

**Issue by cipher1024** [leanprover-community/lean#4]
I'm planning a new community release of Lean and here are the features I would like to include

 * Lean API to the equation compiler
 * Lean API for creating mutually inductive and nested inductive types
 * Lean API for overriding Lean definitions in the VM
 * support for deployment in `leanpkg` (e.g. like `update-mathlib` and `cache-olean`)

**Comment by cipher1024** [comment]
@digama0

**Comment by EdAyers** [comment]
I started writing `vm_override` code https://github.com/EdAyers/lean/tree/vm_override

**Comment by cipher1024** [comment]
Cool! What is the status?

**Comment by EdAyers** [comment]
I got an MVP working. I made a dummy non-meta implementation of floats (@digama0 is working on a real one) and then hooked it up to `native.float` using `vm_override`  The task list is:
- [ ] Do some type checks to make sure that both declarations match up (atm you just crash lean if the types don't line up)
- [ ] There is an issue where Lean will store declarations differently. eg `def d1 | <x,y> := x + y` will be optimised away in the VM to a special projector bytecode and will break `@[vm_override]`. This doesn't happen with `def d2 := \<x,y>, x + y`.
- [ ] write unit tests.

**Comment by EdAyers** [comment]
See also stream:general topic:vm+overrides in Zulip

**Comment by EdAyers** [comment]
@cipher1024 What did you have in mind for the equation compiler?

**Comment by cipher1024** [comment]
That's really cool! Thanks for doing that!

**Comment by cipher1024** [comment]
For the equation compiler, I'd like a richer interface than `environment.add_decl` where we can give a name, a type and a list of equations and it will generate the definition and the related equations. That will make it easier to compile recursive and co-recursive definitions in my data type package.

**Comment by cipher1024** [comment]
What kind of type checking are you thinking of when you're replacing the representation of a type with another?

**Comment by EdAyers** [comment]
The two decls won't have the same type signature but there should be an arity check or something to catch obvious errors. Another idea would be to make the vm_override system have some information about which type is being overloaded so then it could do some more robust typechecks. But that might be too ambitious.

**Comment by cipher1024** [comment]
I think we could do a pretty good job at type checking. If we override a type, we should provide a substitute set of recursor+constructors, then, in the VM, we should be able to treat the type and its overriding type a definitionally equal. With that new assumption, type checking overrides should be the same as normal type checking. @digama0 What do you think?

**Comment by digama0** [comment]
I don't know what you mean by "in the VM, we should be able to treat the type and its overriding type as definitionally equal". In the majority of cases lean can tell that the replacement is not defeq; for example we might replace an inductive type with a pi type or something like that, and lean knows these are not defeq. I don't think you want to identify a type with its overriding type; rather, you want to ensure that all overridden functions are type correct when the override map is applied to all the types.

For example, for quot override, we have `ovr @quot := @id Type`, `ovr @quot.mk := @id`, etc. We could typecheck the override of quot since it has the same type (almost, see below). Then `quot.mk` typechecks because the type is `\Pi A, quot A -> A` and applying the ovr map to this yields the type `Pi A, A -> A` which is also the type of `@id`, and so on.

One problem with this is that `quot` doesn't actually have the same type as `@id Type`, the universes are different. In this case it is solvable with some ulift, but in general I think this is not always possible. Some vm overrides are intended to circumvent universe restrictions, and I think we should treat the VM type system, such as it is, more like system F. For example coinductive types would like to be modeled by their corecursor functions, but this would require the type `Sigma A, A -> F A`, where `A` can live in any type universe. The VM doesn't care about universes. Supporting this might be a lot of trouble, though, so perhaps we can just have an option to disable VM override typechecking when necessary.

**Comment by cipher1024** [comment]
So what is the criterion for accepting or rejecting overrides?

**Comment by digama0** [comment]
Ignoring the universe issues, the typechecking is simply to apply the existing override map to the type of the constant being overridden, and check that the override target has that type. For example, to check `quot.mk : Pi A, quot A -> A` with a vm_override to `quot.mk_override : Pi A, quot_override A -> A`, we replace any vm overrides in the type, i.e. `quot => quot_override`, and then observe that the override target has the overridden type of the source.

**Comment by cipher1024** [comment]
What can we do to make type checking ignore universes? Maybe we could replace every `level` in `expr.const` and `expr.sort` with meta universes as part of the overriding process?

**Comment by digama0** [comment]
We might have to hack the kernel or elaborator to just ignore universe mismatches when we are in this kind of checking mode.

**Comment by cipher1024** [comment]
That's not too appealing. Why do you think using meta universes wouldn't work?

**Comment by digama0** [comment]
I don't think that would accomplish anything. They would just be instantiated during unification, and it would still be a mismatch. For example, if one constant has type Type 2 and it is applied to a function Type 0 -> Type 0 then there are no universe variables to play with.

I think that ignoring universe mismatches is actually the most correct way to handle it, short of defining a shadow copy of expr which has no level argument in `expr.sort`. The levels are still there but they are ignored for the purpose of typechecking, which has the same effect as just removing them.

**Comment by cipher1024** [comment]
Sounds like we need to write our own type checker.

**Comment by digama0** [comment]
Running on the assumption that we would rather not implement another typechecker, the easiest solution is to add a flag in the elaborator's typechecker to ignore universe mismatches, like I said.

**Comment by cipher1024** [comment]
Oh, you also mentioned hacking the kernel which I thought we should avoid

**Comment by EdAyers** [comment]
Can we make a vm_override project page or issue?

**Comment by EdAyers** [comment]
I'll get my branch of vm overrides in to a form that others can fiddle with.

**Comment by cipher1024** [comment]
That's a good idea. I'm good with making either a wiki page or an issue for vm_overrides

**Comment by EdAyers** [comment]
See issue #9

**Comment by khoek** [comment]
Lean `3.5c` or Lean `3.5.0c`? I'm asking the big questions, I know :D

**Comment by cipher1024** [comment]
I wondered ... I think the next revision will be `3.5.1c` but does that mean that the current one should be `3.5.0c`? 

Data should be useful at this point: https://github.com/leanprover-community/lean/releases tells us that `3.4.0` preceded `3.4.1`. That suggests that we should go with `3.5.0c`

**Comment by gebner** [comment]
3.5 has been released.
